set number
syntax on
set autoindent
set cursorline
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
filetype indent on
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
