function pp() {
  /usr/bin/git pull --rebase; /usr/bin/git push
}
function addiff() {
  /usr/bin/git add .; /usr/bin/git diff --staged
}
function btconnect() {
  /usr/bin/bluetoothctl connect $1
}
alias undocommit='/usr/bin/git reset --soft HEAD~1'
alias gc='/usr/bin/git commit -m "$1" $2'
alias rpwd='/usr/bin/openssl rand -hex $1'
alias cls='clear'
alias q='exit'
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
