# Rebase and push
function pp() {
  /usr/bin/git pull --rebase; /usr/bin/git push
}
# Git add all, then show diff changes
function addiff() {
  /usr/bin/git add .; /usr/bin/git diff --staged
}
# Connect to bluetooth
function btconnect() {
  /usr/bin/bluetoothctl connect $1
}
# Does a remote reboot of given ssh-name
function rreboot() {
  ssh -t $1 'sudo /sbin/reboot'
}
alias undocommit='/usr/bin/git reset --soft HEAD~1'
alias rpwd='/usr/bin/openssl rand -hex $1'
alias cls='clear'
alias q='exit'
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
